variables:
  NAME: chrisbuchholz-me
  DOMAIN: chrisbuchholz.me
  DEPLOY_IMAGE: chrisbuchholz/gcloud-kubectl-helm
  DOCKER_REGISTRY: registry.gitlab.com/chrisbuchholz/chrisbuchholz.me
  DOCKER_DRIVER: overlay
  CHART_DIR: chart
  GCLOUD_CLUSTER: schiaparelli
  GCLOUD_ZONE: europe-west1-b
  GCLOUD_PROJECT: schiaparelli-01
  NAMESPACE: chrisbuchholz-me

.shared_hidden_key: &deploy_before_script
  before_script:
    - echo $K8S_CREDENTIALS | base64 -d > k8s_credentials
    - gcloud auth activate-service-account --key-file k8s_credentials
    - gcloud container clusters get-credentials $GCLOUD_CLUSTER --zone $GCLOUD_ZONE --project $GCLOUD_PROJECT 
    - kubectl cluster-info &> /dev/null # needed or else the access_token for the cluster is not created
    - helm init --client-only
    - rm k8s_credentials

stages:
  - setup
  - build
  - review
  - staging
  - production

setup:
  stage: setup
  image: bravissimolabs/alpine-git:latest
  script:
    - echo "export HASH=$(git rev-parse --short=8 $CI_COMMIT_SHA)" >> variables
  artifacts:
    paths:
      - variables

dockerize branch:
  stage: build
  image: docker:latest
  only:
    - branches
  services: 
    - docker:dind
  script:
    - source variables
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker pull $DOCKER_REGISTRY:latest
    - docker build
        --cache-from $DOCKER_REGISTRY:latest
        -t $DOCKER_REGISTRY:$HASH
        -t $DOCKER_REGISTRY:latest .
    - docker push $DOCKER_REGISTRY:$HASH
    - docker push $DOCKER_REGISTRY:latest

docker tag:
  stage: build
  image: docker:latest
  only:
    - tags
  services: 
    - docker:dind
  script:
    - source variables
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker pull $DOCKER_REGISTRY:$HASH
    - docker tag $DOCKER_REGISTRY:$HASH $DOCKER_REGISTRY:$CI_COMMIT_TAG
    - docker tag $DOCKER_REGISTRY:$CI_COMMIT_TAG $DOCKER_REGISTRY:latest
    - docker push $DOCKER_REGISTRY:$CI_COMMIT_TAG
    - docker push $DOCKER_REGISTRY:latest

deploy review:
  stage: review
  image: $DEPLOY_IMAGE
  only:
    - branches
  except:
    - master
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    url: http://$CI_COMMIT_REF_SLUG.review.$DOMAIN/
    on_stop: stop review
  <<: *deploy_before_script
  script:
    - source variables
    - helm upgrade
        -i $NAME-review-$CI_COMMIT_REF_SLUG
        --namespace $NAMESPACE
        --set image.tag=$HASH,ingress.hosts="{$CI_COMMIT_REF_SLUG.review.$DOMAIN}",ingress.basicAuth.secret=default-basic-auth,ingress.tls=false
        $CHART_DIR

stop review:
  stage: review
  image: $DEPLOY_IMAGE
  when: manual
  only:
    - branches
  except:
    - master
  variables:
    GIT_STRATEGY: none
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    action: stop
  <<: *deploy_before_script
  script:
    - source variables
    - helm delete --purge $NAME-review-$CI_COMMIT_REF_SLUG

deploy staging:
  stage: staging
  image: $DEPLOY_IMAGE
  only:
    - master
  environment:
    name: staging
    url: https://staging.$DOMAIN/
  <<: *deploy_before_script
  script:
    - source variables
    - helm upgrade
        -i $NAME-staging
        --namespace $NAMESPACE
        --set image.tag=$HASH,ingress.hosts="{staging.$DOMAIN}",ingress.basicAuth.secret=default-basic-auth,ingress.tlsSecretName=staging-$NAME-tls
        $CHART_DIR

deploy production:
  stage: production
  image: $DEPLOY_IMAGE
  when: manual
  only:
    - tags
  environment:
    name: production
    url: https://$DOMAIN/
  <<: *deploy_before_script
  script:
    - source variables
    - helm upgrade -i $NAME --namespace $NAMESPACE --set image.tag=$CI_COMMIT_TAG $CHART_DIR
