variables:
  IMAGE_REPO: registry.gitlab.com/chrisbuchholz/chrisbuchholz.me
  IMAGE_TAG: $CI_COMMIT_REF_SLUG-${CI_COMMIT_SHA:0:8}
  DOCKER_DRIVER: overlay
  CHART_DIR: chart

stages:
  - docker

build:docker:
  only:
  - dev
  image: docker:latest
  stage: docker
  services: 
  - docker:dind
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  - docker build -t $IMAGE_REPO:$IMAGE_TAG .
  - docker push $IMAGE_REPO:$IMAGE_TAG
