apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name | quote }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ .Release.Name | quote }}
spec:
  replicas: {{ default 1 .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name | quote }}
    spec:
      containers:
      - name: {{ .Chart.Name | quote }}
        image: "registry.gitlab.com/chrisbuchholz/chrisbuchholz.me:{{ .Values.image.tag }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.image.pullPolicy | quote }}
        command:
        {{- range .Values.image.command }}
          - {{ . | quote }}
        {{- end }}
        args:
        {{- range .Values.image.args }}
          - {{ . | quote }}
        {{- end }}
        env:
        {{- range .Values.image.env }}
          - name: {{ .name | quote }}
            value: {{ .value | quote }}
        {{- end }}
        ports:
          - containerPort: {{ .Values.service.port }}
        {{- if .Values.image.volume }}
        volumeMounts:
          - name: {{ .Values.image.volume.name }}
            mountPath: {{ .Values.image.volume.containerPath }}
      {{- end }}
      imagePullSecrets:
        - name: "gitlab-registry-secret"
      {{- if .Values.image.volume }}
      volumes:
        - name: {{ .Values.image.volume.name }}
          hostPath:
            path: {{ .Values.image.volume.hostPath }}
      {{- end }}
